project:
  type: website
<<<<<<< HEAD
  output-dir: ..

jupyter: python3
=======
  output-dir: _site
>>>>>>> main

website:
  title: "ATUS Anual 2024 | Proyecto Final"
  search: true
  navbar:
    background: primary
    left:
      - text: "ATUS Anual 2024 | Proyecto Final"
        href: index.qmd

format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Contenido"
    number-sections: true
    anchor-sections: true
    code-fold: true
    code-tools: true
    code-summary: "Mostrar código"
    code-overflow: wrap
    theme: cosmo
    highlight-style: github
    css: styles.css
    smooth-scroll: true
    fig-align: center
    fontsize: "16px"
    linestretch: 1.6
    mainfont: "Palatino"
    monofont: "Fira Mono"

execute:
  echo: true
  warning: false
  message: false
